blueprint:
  name: MIO - Luces - Simular amanecer y anochecer
  description: Encender luces al amanecer y apagarlos al anochecer
  domain: automation
  source_url: https://github.com/EnriqueBesuman/blueprints/blob/main/light_sunrise_sunset.yaml

  input:
    time_delay:
      name: Tiempo de espera
      description: Desfase horario respecto al amanece para el encendido (Poner en negativo para adelantar la hora de encendido y en positivo para retrasarla)
      default: '01:00:00'
      selector:
        time: {}
    time_offset:
      name: Tiempo de adelanto
      description: Desfase horario respecto al anochecer para el apagado (Poner en negativo para adelantar la hora de encendido y en positivo para retrasarla)
      default: "-1:00:00"
      selector:
        time: {}
    light_target:
      name: Luces
      default: []
      selector:
        entity:
          multiple: true
          filter:
          - domain: light

trigger:
  - platform: sun
    event: sunrise
    offset: !input time_delay
  - platform: sun
    event: sunset
    offset: !input time_offset

action: 
    sequence:
    - service: >
        {% if trigger.event == "sunrise" %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}
      target:
          entity_id: !input light_target
