blueprint:
  name: MIO - Switch - Amanecer anochecer
  description: Encender interruptores al amanecer y apagarlos al anochecer
  domain: automation

  input:
    time_delay:
      name: Tiempo de espera
      description: Desfase horario respecto al amanece para el encendido (Poner en negativo para adelantar la hora de encendido y en positivo para retrasarla)
      default: '01:00:00'
      selector:
        time: {}
    time_offset:
      name: Tiempo de adelanto
      description: Desfase horario respecto al anochecer para el apagado (Poner en negativo para adelantar la hora de encendido y en positivo para retrasarla)
      default: "-1:00:00"
      selector:
        time: {}
    switch_target:
      name: Interruptores
      selector:
        entity:
          multiple: true
          filter:
          - domain: switch

trigger:
  - platform: sun
    event: sunrise
    offset: !input time_delay
  - platform: sun
    event: sunset
    offset: !input time_offset

action: 
  - service: >
      {% if trigger.event == "sunrise" %}
        switch.turn_on
      {% else %}
        switch.turn_off
      {% endif %}
    target: !input switch_target