blueprint:
  name: MIO - Control de Luces
  description: "Enciende y apaga Luces en función de los siguientes supuestos:\n\n
    > - Cuando se activa un **Sensor Binario** (y según un desfase de tiempo opcional).\n
    > - Y/o Cuando **Amanece o Anochece** (también según un desfase de tiempo opcional, y el
    modo de funcionamiento **Diurno o Nocturno**).\n
    > - Según un determinado nivel de **luminosidad** (aplica en cualquiera de los casos anteriores).\n\n\n
    **Version**: 1.0.0\n\n**Documentación:** Estamos trabajando en ello, pero creo que es bastante auto-explicativo..."
  domain: automation
  source_url: https://github.com/EnriqueBesuman/blueprints/blob/main/castellano/light_control.yaml
  input:
    luces:
      name: Luces
      description: "`required`\n\n
        Luces que se encenderán o apagarán."
      selector:
        entity:
          multiple: true
          filter:
          - domain:
            - light

    activador:
      name: Activador
      description: "`optional`\n\n
        Sensor Binario que apaga o enciende las luces (además de al amanecer o anochecer,
        si se selecciona)."
      default: []
      selector:
        entity:
          multiple: false
          filter:
          - domain:
            - binary_sensor
    solo_noche:
      name: Solo por la noche
      description: ">`optional`\n\n 
        >Enciende y apaga las luces, únicamente por la noche (independiente de al amanecer o anochecer).\n
        >ÚNICAMENTE TIENE EFECTO SI SE SELECCIONA UN SENSOR BINARIO."
      default: false
      selector:
        boolean: {}
    espera:
      name: "Espera encendidas"
      description: ">`optional`\n\n 
        >Tiempo que permanecen encendidas las luces desde la última  desactivación del sensor.\n
        >ÚNICAMENTE TIENE EFECTO SI SE SELECCIONA UN SENSOR BINARIO."
      default: 00:01:00

    anochecer_amanecer:
      name: Considerar anochecer y amanecer
      description: "`required`\n\n 
        Enciende y apaga las luces, después del anochecer y antes del amanecer (además de según el sensor binario, si se selecciona)."
      default: false
      selector:
        boolean: {}
    modo:
      name: Modo de funcionamiento
      description: ">`optional`\n\n 
        >En modo diurno, se encederán las luces al amanecer y se apagarán al anochecer.\n 
        >En modo nocturno, se encenderan las luces al anochecer, y se apagarán al amanecer.\n
        >ÚNICAMENTE TIENE EFECTO SI SE CONSIDERA EL ANOCHECER-AMANECER"
      default: diurno
      selector:
        select:
          options:
          - diurno
          - nocturno
          multiple: false
          custom_value: false
    time_delay:
      name: Tiempo de espera
      description: ">`optional`\n\n 
        >Desfase horario respecto al amanecer para el encendido o apagado.\n 
        >Poner en negativo para adelantar la hora de encendido y en positivo para retrasarla.\n
        >ÚNICAMENTE TIENE EFECTO SI SE CONSIDERA EL ANOCHECER-AMANECER"
      default: 00:30:00
      selector:
        time: {}
    time_offset:
      name: Tiempo de adelanto
      description: ">`optional`\n\n
        >Desfase horario respecto al anochecer para el apagado o encendido.\n
        >Poner en negativo para adelantar la hora de encendido y en positivo para retrasarla.\n
        >ÚNICAMENTE TIENE EFECTO SI SE CONSIDERA EL ANOCHECER-AMANECER"
      default: '00:-30:00'
      selector:
        time: {}

    sensor_luminancia:
      name: Sensor de luminosidad
      description: "`optional`\n\n
        Entidad de medición de luminosidad.\n
        TIENE EFECTO EN TODOS LOS ESCENARIOS."
      default: []
      selector:
        entity:
          multiple: false
          filter:
          - device_class:
            - illuminance
    luminancia:
      name: Nivel máximo de Luminosidad (lux)
      description: ">`optional`\n\n
        >Nivel máximo de luminosidad (lux). Si la luminosidad medida es superior, las luces no se encenderán.\n
        >ÚNICAMENTE TIENE EFECTO SI SE SELECCIONA UN SENSOR DE LUMINOSIDAD."
      default: 300
      selector:
        number:
          min: 0
          max: 100000
          unit_of_measurement: lx
          mode: box
          step: 1
variables:

  activador: !input activador
  luces: !input luces
  anochecer_amanecer: !input anochecer_amanecer
  sensor_luminancia: !input sensor_luminancia
  luminancia: !input luminancia
  solo_noche: !input solo_noche

trigger:

- platform: state
  entity_id: !input activador
  to: 'off'
  for: !input espera
  id: activador_off
- platform: state
  entity_id: !input activador
  to: 'on'
  id: activador_on

- platform: sun
  event: sunrise
  offset: !input time_delay
  id: sunrise
- platform: sun
  event: sunset
  offset: !input time_offset
  id: sunset

condition:
  - condition: template
    value_template: >
      {{ (sensor_luminancia | length == 0) or
        (sensor_luminancia | length > 0 and
        states(sensor_luminancia) | float(0) <= luminancia | float(0)) }}

action:

  - if:
      - condition: trigger
        id:
          - sunrise
    then:
      - service: light.turn_{{ iif (modo == "diurno", "on", "off") }}
        target:
          entity_id: !input luces
  - if:
      - condition: trigger
        id:
          - sunset
    then:
      - service: light.turn_{{ iif (modo == "diurno", "off", "on") }}
        target:
          entity_id: !input luces

  - if:
      - condition: trigger
        id:
          - activador_off
          - activador_on
    then:
      - if:
          - condition: template
            value_template: >
              {{ ( not solo_noche) or 
              (solo_noche and states('sun.sun') == 'below_horizon') }}
        then:
          - service: light.turn_{{ states(activador) }}
            data:
              entity_id: '{{ luces }}'

mode: single
